#!/bin/sh
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrrP5nvaKkSh6VpCwAkDwyaYXAr2tyGrjA5hb2Sus9SCsJdrQMMh -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qn2H9WhvP2K6EhknZmceV2ZUUyFxbEgDJ4QcJVMKgd8UGCac6b6W -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpFCJYjcxgqnaQyKCfpJHb3WvTS6TMDEeJzoE1P2XzTbSvRCFumb -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqUyUbyS4sJXjnwPPRf6yQ1kPoevnKGdx1p41a1QxDg6h1Ao7Ltf -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnfqxFnjr6nnA1x9nLGtBYLVtW95pEkT5gj5HbZMxCS49t42vW64 -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnyUKmq72EU7AVXoauMBv3FpmX6mGudKNwEZCDX1CTYfBRcxi6b8 -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqA4r5bZqH3RdxPmuv46WRkcqENbmMUmJe3s1ZRQdCWQ79y6HbE5 -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpkjb4GPjgP1rg5gdRiEqnPiV4dT74WMhFJ3Cpjo7LFxLe2vVaTQ -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qihVH8JHtmu3Ky83xMdWTtFzBNSY2Dwx9VLJdn5e2Rox1YbkYHEN -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrViSCmuryS1KiRnk28TTc8QeasZtBardb6UyUKVvQenkurzPmto -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qieMAU4XjiRdafVccoFcQXc47Z1wTpGiEd9ujwN9AmFjwzUHKAcZ -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmZny9wvkKp9yEhRzN2rHtB8MGuep3dETXiwLjfhbHuJqKwcijcb -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnJBviqvT61Cou9ZhcYriCfyB2aEfoJ8jzhruh5Zn3AGCzZBWhGh -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qowoiHdJKyTdMS8xwtiKnFUu7e935KrsGsnHsbXCZnH2PDjW5Qso -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qojmpAdnsbyax75Md67Dw27Pv1eqhv4NvFa8Uv63xrSyabMe5dzH -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqaGsCzFBFL1NAzEPELrNm2ftxJujETDeGsWXcengyqyYdJFtBgr -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqfQ2v8LXYBazij1V7VYRhLqv8YDaf6gHjANRxNPytieyvUybmUz -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qns2egmDKDeaKvhyZ9rR7h4hdA758UQtuBCmYqek25tj7nMn3nPQ -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnkeZjBUEDp7R8CuK3vc1cjsEX1bQ4FDsCM3Bpr3RVv5PrhbxJ3i -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qr1EnPPkHwMDdwjFvf52GaaT4FmhFxZDMH3skMh5v2A1GmZuAaMr -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrk8qcP8H92Keq25VxdQazyxqMduFwpoViS7ZLsJCUNvVLDsbSns -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoMtFUHwc14hUt3aUNeZwYNNAK7iKiWqkKP6cPp2xbFGxqPDabAQ -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qifEJTcMr1oVYFKttj9hTByy9GuyWq1mfnDjYpPLjPeUYx4RhGyB -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqeoJsWhYSv6pJCk27d8Jxks6tou3hcZBnWc4KacX66sq6YLvMJG -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpELqmbe1sN7dvqSE1ijf1EyZvnqJuUsLapBHRW8wYCS3j1mGxuw -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpxLJEFsipoY9qa44UFNTgAAMiTm7b7zdPdFEbZ46ZUaRsdTYMTn -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qkeHp7PNQdAc9yvgnEcQe8MJEGspYj83CPfvk7wrSwHXUHDv5atS -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoSAk9kQrAz5mp5CbzE1W7GoL4gD6TzZm2BNQT6opAAFX4CS1zkU -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qovStxz47rNCDmBWo5UpVomYAWZjzvM4BUKFw4bRooXnYxVKpK4k -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrZyVicZufukRfyLUvp8EvabdcctffNUADehz7L5wZomPYDKrrWn -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qq6pVBLUcw1VnqiHRKrLigAkfUFQnPwXgeEYW8DVrUxhWxu47pPp -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qr592FuYxyPsdza6Cf52uUna5ALNoQMvLNZ1PMwEfEpta1NRpLxS -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qii9JDoPWnPfZ43FrboPrJm4tqmeGea4KL7nbU9VKqu9EM3wiVUP -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qiUHpkaMiGd2WSDwcgehKYbCFLWjii8gDcZKdF6YjcrHAv9nX17u -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnDftGfpAC1J5ufYLyuHQ7zD3oJ5nPEzG7xPEK8zrnfEqHArwhGF -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnuLWaKVk6AWTXz8pLJxJh7WjzGFwvPPkVDt14inqFH6BiVDYDro -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoexycG8ka2B6oWx8QJfQC9AVeoV3SabsViFJgLURgwhnmodoYkG -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpXZwdNZDotFZ9U6FX3D8bBFEi94unBYwd6GA3G2NBVTumeC2PxV -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqsNfypDxYqPSBqS1RF5VpY3xefET17dXeYRKFLZEnX3mkgwQi1V -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoPh8GsuKjFjoU63BMpaD8HrLCKejdqrJfZf1Xqy6Xsze9JYZ9gd -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnTYeiYqnnjzB28b2MHeX6uCE7QbXhoQH82KHk89ETTNyGDMjhQb -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoZsJNvST3P2MF98ZHcW4S44jQujA5fjR6P8ZdQB75twLQ99FJ7j -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpymMmYqFZpxtkjis6cP68x17muQAqYG35iNyQD96mMQSqsUreJb -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrjprSrx3hqjS3KjXxLAeejQDxtESDF1pTx44AdRadamWj5A6mM3 -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpcGHFMewiDfMYsTxw3modCNPaRH1hYfyvBxLwwJhwH9EUYgbYNd -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qo72p4MvCnwjSH4p1cCzdiMyAKaY35HiADKTWdj3kksRRs8H96nu -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qkeCJmnK4LU2CSirvzaUzHGHQBMTzCcCKkCooFB581Wn9dKFU1tu -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qp6d2isb1wBNvzmjhFgt4pz1hReiDyv6k33M5vGKJ2QpyY9ErFPB -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qiqqSkiTuFZJWt8nULKvyjsZUJUXojwN2paMF6P1SKkB1U84eKMT -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqoqMW2BAcdDFBtHjFmdxr1Ah4tRCHZTEefn1EVGgc22A7CVtnVW -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qntbFdtPFeCzpLaJBy3YgDKmuyBFHC7NNEHGMTWRaps3KH7c6PLk -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmFbeqbbg7MrJ57DPr7RDULHbrFHkahky3ZqpUnSNTZWo32AbjZY -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoAd6SD5pN1aMLpky183cLShFu57gzAWBderjur5PxrokdexPV8Q -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qp3ZqvVNW1qCYyM5FbFrFXsgXGyG5wAFykWJyLzgfTdLeDw2qKGs -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnF2MBmcfM3vJwYeaMgTdNQMqt1NLnRArfV6EUUdvQ7qQ3nbsSDP -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoqF3smPypbnGwdT1DqApS9oBqNch9pjy3rrqduui2kA2r3bPMRn -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqFbwAuRbtADodAZZTngCV4d1Yrn7NvtguSUh47HPNKijnNdEGjM -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qkqWjAy79d5fpckgXy35ayUZiJMkJ8F2E26EB7Q9rBs4KMQRMPuK -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qis3gW74zKaMTR5w9gnJjcXfPjeFBZr2mPjrSFt3PTXFM26iffmj -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qitj2oddFCe2Fk3YhpuSokCPtMpUApE92HCzrDbjmvqv86utURc7 -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qox4uGVEJqDXh9jYt8EXVa85sk5VXaNy6tpP1eLqVEPkYUymzhgc -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpoRuJHSrXxPim24dAJBYbPm1toBjK5aGMD1TMPkBXVz9vTv7TF7 -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrcDgpUjAxcWUZNaDGCMQqrZY8oTBVvTZaWdGkwKoPCbDduXvtzc -fee 1 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qiv5unGDVVp4Trbxd2dH1G6LctwfFk1GHuof4NYzdBbrbgVYf7ub -fee 1 -amount 0.001