#!/bin/sh
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoWjj77gk6UD55nAPMr8NeTwVgXGiannrZ34cmfjamuJjG3YNH5K -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qj7JjRrNfTBAUo9seVTxGBZsr4Zd3iCcoEQEeL9TN2JamefBZRVH -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmtS1GNjgqBs4n5FKsGMFYYuspGmLtrJmxGtNPtc6gpHMWV45SgT -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qknuGAmW8ZB82yZ5xU245fBGCPJxavL8EtxDHgkqnoS1KEo3mpEC -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qka2yxv6QHgUuyzxn47HMpReYuWrrGi2NqWZHVGLaoZZxPgc5rGU -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpCdnMgLC5YzXM3qrqybsqHB35UFHHt9muUDuAm2d1ny1ZqEDJzh -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpB1oBckU1wXkRFxcwwCheq3chiKtVhY6T3q8aQiwJUaoCjpqgXS -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qn6xwANH3jgqqxyqmDEHK5a3jbVd54p2oBdahRuMLmL7qfAxXWGF -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qo72jZRuVGbGsVg6JtEGWiLTns14mMzAo3LAyNupk27vXCFLNdyp -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmfrWwaUR38Lbc5uW4kF5fQFX532FLk5D8xHjgfZGxYNLoR6Geib -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qiptquSVjVM3rNYarUta8g1qgxfKus931RAnheNKX6LxssJbRiYf -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjHfkNwKwhTDnsYVsfxaTfioqL5FahmHZXnAwb1xA7Exf3JPA88f -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqXnsmUNXibyfBwf3ADyopwW1tTJDPZWnFhRdFfjRHjRjp634AzL -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmoXaUbQKMMPA1n71ZrWrB3dnFQ5gJF4uBVfVTdMejZd5eWZwmNX -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnQU1du13WLpTiGjh7q3sGemwrsPnD3m3tVBi5vG7cF6jJqKppPv -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnX51MmGERb9SoYVJy1GuxAU6LmyfH8BGNZxgyNu3W739KvKWnTL -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqFWuVHQ5DgD5zEt3PqNMgRQPCdspQeQitZoD5ArxXoCa97svXSh -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqiuSjeZDbTrxvcnxXfq4Z4R9CsFC9BCuuVuHiwUQ6ErNyJ717Az -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnkduerf3PE2P6XpoHRJJbnC5ZW5Pk4UEhBUCUjnmUqABoJ7yYdL -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjFSYt7v7wHBbp9orkUV34xhqSNs5RLhY4UfwCWEQEiXrst8Hi4j -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmL7bWrMRuYr8hCT9p7L7jUho7oajSTohtFYSr8XYM3QoWyf8VL6 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qkNSyk5nXoy45pCckV9hcFm528b8BomA6iqX55tZLhEbuQf3QfRw -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qni5QapAft1HvfdpAofPT6j4bXUeUb1mwyLuwV2vUkG7PLLiLc2s -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjqu74ZHWBbVkStwaPnhySB7U4bokQ4hndpztejmVTHgE9iSKLKs -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qqAr2AjhN3v5Zxk1oGkq8UZySCCev1PsBAxP9Uw3eqm3cYPoDEHY -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoE9wDH7RWW6sAqPQJ5KFEkypLt3cH4DeuJTsieQY5gxNYsbEuNT -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qoyzuqvzWhzmeKn65aLPLQU66UxWgS8dkDaYyrTmJU18ViPNJmQt -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qkL8sWE3rsvjAFSZxh1i2yNzoqkJCRX234B5NmXoiHH9t3wMYo1T -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmCcPoUgU2gjssXRNceHmrkKwyict1QAGjGFeAu9ow8ETbAaPv14 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qo4RsTou54M7A3nuQgeKgXgtPhMmy2m2JKy9czoGVdsGbpqLLLfM -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjPiM2hPCv4qogPYxDuz3U1UidPp7RRijjb2e2NcnTxq8GHyWb1a -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qizP44x4FJB746LRk6KCQQ1qNAFHKe9pDECzbJagZvriduXTx7zK -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnyS9n4evSWTfHBpEYkpd7rNW2B2Tq5tEunQ6AB3vfdwjZtzs7Hh -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjuZQtnxQn9kjq6NB8Z72Z8Sar9dKoATZnMcswgjRrkxLhbw6pYL -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrviTZWcGgxapZ7vNrZ8qVMyHDoPbzzMwjWMyubv72KhJCFH46G5 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpgJJN3ZE56rVN8Q8Gx6XsGMkiESqDnnjAC8AtLrkioxqo2gD4wt -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qk3xgJkeMVbULnQFae7GnphpwMALBSkopgFk8GutYkg9LpN584aY -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmDh1WRBB8Ttz4PXFeuUs5wHdWbwZJYxTVeTV6RisWdPpitKHaaE -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qo41nuz2vKbTBPSVfBxLMVtm3ZEkE27JrRd7CGMtfSShh9frUBeT -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrq48z9jS43McAWmNLxAP11fjxNRizjpBTay64gt3oct9BuFdAi5 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpBPT47UfVL9jSDDwu9Zpa6X5ih2VWpjuYepfoBximLwyMWkALu9 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrdXFZrDmkjpsSJRtjYtmEZ7utmrndWSiiepx7SJbtQRR5M85n7h -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qp4DJFykPmnmrYvFk9VPiF7HXwgbNYZtX7pfFZfv6JnfrYjnFChx -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qp4bUqszXepSVoF1pLB4nifvxcQciwDg8CxmJukjy9dVuHJs3zTC -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qq4ZCbx6MRy9qvsrBzh64q2CEGqVsvSSKvYRWTu736cY8SsRxTra -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qndJi5mnRoBZ8SAYDM1oR2SgAk5WpZC8hGpJUZ4e64kDHGbFMeLJ -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qkwTF9uhc3pzWqy4c9BUZczKkUkTp8iR42YKQKhwAwbQtw9A8scn -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmrJCGXwsSekweHFo9FpuuRzM4gm86ujH4UVhPBWLTPvteQ3M838 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qj7HaX7dX75yusvPXfJ7nM3vJqwajENaBXKeTaKotGBzMgnbXDeu -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qpvasYTfoYf11ieeEEKkCg9BwEfpXBTSPS6D5WUfwghm4GgeVjcr -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qm1UuFDG6GSQ1Av2r1FULLJH6GAHuDNg14wSX5NaCZDVJnMWx46V -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmUiHg9Ws1kHQTwsD89FF43xdqEGcBxqbVR4VnHs27y8DQ3GP7n8 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qq5ASta6VnFGRbZNmcwqJMwC4Pvqy2ptpMZSJF7hmNygubauKn4f -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qihuSQySZB2HRQDwnsDQ2WxyADALjZq1GwShyDEe3hJWJppLkbnE -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjW4wkRcDv3Z6GWd83LK4NcGe6id4fKPmNybjFSDvCDs5uizf8Lj -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qr4uPp1pLkbhrx22NLPJfmPWCwtDxxwHySqNLWaPUTe7khSAKhEC -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjq3AXwLVkR7EKuX7BZPUPoPedpbDViQQD7oFKayiomcPDoj6mLt -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qjj4sUC3VPzwNtE3pF37xgruwC8BikEQRpdYMjGnCjPM4Qk9YvB6 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qisCrjM9eNrr6qoGM2g5qcnQrcMTYMgSiWB5hsTNDjZ9VKE7uC71 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qrkmZtoR8zmVuV1MtVVAGZ31rEHRDiXL1YBj1mHPg8husf9ZBGmM -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmPfCSkCehqavkyQw2s99GWy7SbbxpMJMWSHHpssEVSfoXtT4Zke -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qnabKMHooodHbUCnN1kun3Jpfuth2pHPnK6KoaJZ1hPQjbpkFqZ5 -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qmfS8M6naWa1jNeZT12jfxLmngSdg2TZzTcz7skt5CzmhTTiixYM -fee 60 -amount 0.001
sudo docker exec -it mina coda client send-payment -sender $MINA_PUBLIC_KEY -receiver B62qj6mKfy4VJt16ZHCBurBc5qbVtYaNKoxqt9MMTUuEKESYr39vXUH -fee 60 -amount 0.001